# Generated by Django 5.0.6 on 2024-10-10 11:44

import django.core.validators
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('sku', shortuuid.django_fields.ShortUUIDField(alphabet='0123456789abcdefghij', db_index=True, length=22, max_length=20, prefix='', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField()),
                ('sku', shortuuid.django_fields.ShortUUIDField(alphabet='0123456789abcdefghij', db_index=True, length=22, max_length=20, prefix='', unique=True)),
            ],
            options={
                'verbose_name': 'Frequently Asked Question',
                'verbose_name_plural': 'Frequently Asked Questions',
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('description', models.TextField(blank=True, null=True)),
                ('sku', shortuuid.django_fields.ShortUUIDField(alphabet='0123456789abcdefghij', db_index=True, length=22, max_length=20, prefix='', unique=True)),
            ],
            options={
                'verbose_name': 'Gallery Item',
                'verbose_name_plural': 'Gallery Items',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sku', shortuuid.django_fields.ShortUUIDField(alphabet='0123456789abcdefghij', db_index=True, length=22, max_length=20, prefix='', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('rate', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('sku', shortuuid.django_fields.ShortUUIDField(alphabet='0123456789abcdefghij', db_index=True, length=22, max_length=20, prefix='', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('date_subscribed', models.DateField(auto_now_add=True)),
                ('sku', shortuuid.django_fields.ShortUUIDField(alphabet='0123456789abcdefghij', db_index=True, length=22, max_length=20, prefix='', unique=True)),
            ],
        ),
    ]
