# Generated by Django 5.0.6 on 2024-10-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_project_image_alter_project_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='content',
            field=models.CharField(max_length=255),
        ),
    ]
